### PR TITLE
feat: add prop displaySlider

### PR DESCRIPTION
**Pull request by RbkCp**
This prop can be used to show or hide product slider.
For example, if I have only one product image I don't want to show slider.

### CODE REVIEW

**Comment by akulubala** [comment]
Hi @RbkCp, for now this pull request can't merge into this plugin, because inside container effect need  slide

**Comment by RbkCp** [comment]
I think you misunderstood me here.
This PR is backward compatible, and simply add one prop that can be used to hide the thumb-list.
Why wouldn't you merge it ?

**Comment by RbkCp** [comment]
image
In this case (I have only one product image), I don't want to show thumb-list but I want to keep zoom-image feature.

**Comment by akulubala** [comment]
Hi @RbkCp there have three effects. First 'With A Pane Container Zoomer', Second 'Inside Zoomer Container With Round Effect', third one 'Inside Zoomer Container', the third one need this slide div, so it can't be simple remove like this. Check the example page  https://akulubala.github.io/vue-product-zoomer/

**Pull request closed without merging**
